export const CONTENT_REQUEST = 'CONTENT_REQUEST'
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS'
export const CONTENT_FAILURE = 'CONTENT_FAILURE'

export const CONTENT_RANK_REQUEST = 'CONTENT_RANK_REQUEST'
export const CONTENT_RANK_SUCCESS = 'CONTENT_RANK_SUCCESS'
export const CONTENT_RANK_FAILURE = 'CONTENT_RANK_FAILURE'